MainApp/urls.py
#the path function, which is needed when mapping URLs to views 
from django.urls import path

#the dot tells Python to import the views.py module from 
# the same directory as the current urls.py module. 
from . import views

#The variable app_name helps Django distinguish this urls.py file from 
# files of the same name in other apps within the project
app_name = 'MainApp'

#The variable urlpatterns in this module is a list of individual pages 
# that can be requested from the MainApp app 
urlpatterns = [
    #the first argument is an empty string ('') which matches the 
    # base URL - http://localhost:8000/. the second argument specifies
    # the function name to call in views.py. the third argument provides
    # the name 'index' for this URL pattern to refer to it later
    path('', views.index, name='index'),
    path('topics',views.topics, name='topics'),
    # the integer value is stored in the variable topic_id and will
    # be subsequently passed to the topic function in views.py
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    ]

    

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MainApp.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
#We import the path function, and then import the include function so we can 
# include some default authentication URLs that Django has defined.
from django.urls import path, include

from . import views


app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    ]

MainApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Topic(models.Model):
    text = models.CharField(max_length=200)
    # auto_now_add=True - set this attribute to the current date and time
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        # it allows us to set a special attribute telling Django to use 'Entries'
        # when it needs to refer to more than one entry. Without this, Django
        # would refer to multiple entries as 'Entrys'.
        verbose_name_plural = "entries"

    def __str__(self):
        return f"{self.text[:50]}..."

MainApp/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}


 #A widget is an HTML form element, such as a single-line text box, 
        # multi-line text area, or drop-down list. 
        # customize the input widget for the field 'text' so the text area 
        # will be 80 columns wide instead of the default 40

MainApp/views.py
from django.shortcuts import render, redirect
from .forms import TopicForm,EntryForm
from .models import Topic, Entry

from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.

# When a URL request matches the pattern we just defined, 
# Django looks for a function called index() in the views.py file. 

def index(request):
    """The home page for Learning Log."""
    return render(request, 'MainApp/index.html')


@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    #A context is a dictionary in which the keys are names we’ll use 
    # in the template to access the data, and the values are the data
    #  we need to send to the template. In this case, there’s one key-value pair, 
    # which contains the set of topics we’ll display on the page. 
    context = {'topics':topics}
    #When building a page that uses data, we pass the context variable to render() 
    # as well as the request object and the path to the template 
    return render(request, 'MainApp/topics.html', context)

@login_required
def topic(request, topic_id):
    #just like we did in MyShell.py
    topic = Topic.objects.get(id=topic_id)
     # Make sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404
    # foreign key can be accessed using '_set'
    entries = topic.entry_set.order_by('-date_added') # -date_added is descending order
    context = {'topic':topic, 'entries':entries}

    return render(request, 'MainApp/topic.html',context)



@login_required
def new_topic(request):
    if request.method != 'POST':
        # No data submitted; create a blank form (create an instance of TopicForm).
        # Because we included no arguments when instantiating TopicForm, Django 
        # creates a blank form that the user can fill out.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        # We make an instance of TopicForm and pass it the data entered by the user, 
        # stored in request.POST.
        form = TopicForm(data=request.POST)
        #The is_valid() method checks that all required fields have been filled 
        # in (all fields in a form are required by default) and that the data entered 
        # matches the field types expected
        if form.is_valid():
            #write the data from the form to the database
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            #redirect the user’s browser to the topics page
            return redirect('MainApp:topics')

    # Display a blank form using the new_topic.html template.
    context = {'form': form}
    return render(request, 'MainApp/new_topic.html', context)

@login_required
def new_entry(request,topic_id):
    topic =  Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
            raise Http404
    if request.method != 'POST':
        form = EntryForm()      #blank form
    else:
        form = EntryForm(data=request.POST)

        if form.is_valid():
            # When we call save(), we include the argument commit=False to tell Django to create 
            # a new entry object and assign it to new_entry without saving it to the database yet.      
            new_entry = form.save(commit=False)
            # assign the topic of the new entry based on the topic we pulled from topic_id
            new_entry.topic = topic
            new_entry.save()
            return redirect('MainApp:topic',topic_id=topic_id)

    context = {'form': form, 'topic': topic}
    return render(request, 'MainApp/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        # This argument tells Django to create the form prefilled 
        # with information from the existing entry object. 
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('MainApp:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'MainApp/edit_entry.html', context)

MainApp/templates/MainApp/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}

    </head>

    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'MainApp:index'%}">Learning Log</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'MainApp:topics'%}">Topics</a></li>  
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                
                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
              </ul>
        </div>

        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>

            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>

    </body>




</html>

MainApp/templates/MainApp/edit_entry.html
{% extends "MainApp/base.html" %}

{% block content %}

  <p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Edit entry:</p>
    
  <form action="{% url 'MainApp:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

MainApp/templates/MainApp/index.html
{% extends "MainApp/base.html" %}

{% block page_header %}
    <div class="jumbotron">
       <h1 class="display-3">Track your learning.</h1>
            <p class="lead">Make your own Learning Log, and keep a list of the
            topics you're learning about. Whenever you learn something new
            about a topic, make an entry summarizing what you've learned.
            </p>

            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>
{% endblock page_header %}

MainApp/templates/MainApp/new_entry.html
{% extends "MainApp/base.html" %}

   {% block content %}

    <!-- includes the topic_id value in the URL, so the view function can associate 
      the new entry with the correct topic-->
    <p><a href="{% url 'MainApp:topic' topic.id %}">{{ topic }}</a></p>

     <p>Add a new entry:</p>

    <form action="{% url 'MainApp:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      
     <button name="submit">Add entry</button>
    </form>

   {% endblock content %}

   

MainApp/templates/MainApp/new_topic.html
{% extends "MainApp/base.html" %}

   {% block content %}
     <p>Add a new topic:</p>

     <!--define an HTML form. The action argument tells the browser where 
        to send the data submitted in the form-->
    <form action="{% url 'MainApp:new_topic' %}" method='post'>
        
      <!--Django uses the template tag {% csrf_token %} to prevent attackers 
        from using the form to gain unauthorized access to the server-->
      {% csrf_token %}

      <!--We only need to include the template variable {{ form.as_p }} for 
        Django to create all the fields necessary to display the form automatically.
        The as_p modifier tells Django to render all the form elements in paragraph format,
        as a simple way to display the form neatly.-->
      {{ form.as_p }}

      <!--create a submit button-->
     <button name="submit">Add topic</button>
    </form>

   {% endblock content %}

MainApp/templates/MainApp/topic.html
{% extends "MainApp/base.html" %}

{% block page_header %}
  <h1>{{ topic }}</h1>
{% endblock page_header %}

{% block content %}

  <p>Topic: {{ topic }} </p>

 
     {% for entry in entries %}
     <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
       <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
         <small><a href="{% url 'MainApp:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
       <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
     {% empty %}  <!-- if the list is empty then display message-->
      <p> There are no entries for this topic yet.<p>
     {% endfor %}

  <p>
   <a href="{% url 'MainApp:new_entry' topic.id %}">Add new entry</a>
 </p> 


{% endblock content %}

MainApp/templates/MainApp/topics.html
{% extends "MainApp/base.html" %}

{% block page_header %}
   <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

  <p>Topics</p>

  <!--In standard HTML, a bulleted list is called an unordered list 
    and is indicated by the tags <ul></ul>. -->
  <ul class="list-group border-bottom pb-2 mb-4">
      <!-- for loop to loop through each topic
       NOTE: not like python, needs a endfor -->
     {% for topic in topics %}

     <!-- To print a variable in a template, wrap the 
        variable name in double braces. -->
      <li class="list-group-item border-0">
        <a href="{% url 'MainApp:topic' topic.id %}">
          {{ topic.text }}</a>
      </li>
     {% empty %}  <!-- if the list is empty then display message-->
       <li class="list-group-item border-0">No topics have been added yet.</li>
     {% endfor %}
  </ul>

  <a href="{% url 'MainApp:new_topic' %}">Add a new topic</a>

{% endblock content %}